### ISSUE TITLE
`git rev-list` failed when updating stack

### ISSUE THREAD

**Issue by amyreese** [ezyang/ghstack#143]
```
amethyst@luxray ~/workspace/LibCST path-metadata  » ghstack
$ git remote get-url upstream
$ git fetch --prune upstream
$ git merge-base upstream/main HEAD
$ git rev-list --header '^71183c65d7937624a4220bc075b0bf393af4b444' HEAD
$ git rev-list --header '^71183c65d7937624a4220bc075b0bf393af4b444^@' 71183c65d7937624a4220bc075b0bf393af4b444
$ git rev-parse --show-toplevel
$ git config --default /Users/amethyst/workspace/LibCST/.git/hooks --get core.hooksPath
$ git rev-list --max-count=1 --header upstream/gh/amyreese/1/orig
fatal: ambiguous argument 'upstream/gh/amyreese/1/orig': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
ERROR: Fatal exception
Traceback (most recent call last):
  File "/Users/amethyst/.local/pipx/venvs/ghstack/lib/python3.10/site-packages/ghstack/logs.py", line 107, in manager
    yield
  File "/Users/amethyst/.local/pipx/venvs/ghstack/lib/python3.10/site-packages/ghstack/__main__.py", line 101, in main
    ghstack.submit.main(
  File "/Users/amethyst/.local/pipx/venvs/ghstack/lib/python3.10/site-packages/ghstack/submit.py", line 203, in main
    submitter.prepare_updates()
  File "/Users/amethyst/.local/pipx/venvs/ghstack/lib/python3.10/site-packages/ghstack/submit.py", line 918, in prepare_updates
    d = self.elaborate_diff(s, is_ghexport=is_ghexport)
  File "/Users/amethyst/.local/pipx/venvs/ghstack/lib/python3.10/site-packages/ghstack/submit.py", line 494, in elaborate_diff
    self.sh.git(
  File "/Users/amethyst/.local/pipx/venvs/ghstack/lib/python3.10/site-packages/ghstack/shell.py", line 278, in git
    return self._maybe_rstrip(self.sh(*(("git",) + args), **kwargs))
  File "/Users/amethyst/.local/pipx/venvs/ghstack/lib/python3.10/site-packages/ghstack/shell.py", line 210, in sh
    raise RuntimeError(
RuntimeError: git rev-list --max-count=1 --header upstream/gh/amyreese/1/orig failed with exit code 128
```

ghstack rage: https://gist.github.com/0f28e8d41b45467b9e281a7a5eb3771a

**Comment by amyreese** [comment]
Looks like this was because my `.git/config` for that repo was only set up to sync the `main` branch, for reasons I don't understand:

```
[remote "upstream"]
    url = git@github.com:Instagram/LibCST.git
    fetch = +refs/heads/main:refs/remotes/upstream/main
    gh-resolved = base
```

Replacing `main` with `*` on both sides of the `fetch` option resolved this issue.  Perhaps this is something we should validate somewhere in ghstack?

**Comment by amyreese** [comment]
I believe this is also why I was encountering errors with this project — it had a similar git config. I think this might be the way that the `gh` tool clones from forked repos, with the expectation that upstream branches don't matter. Then trying to use `ghstack` with that git config blows up.

I'll look at adding a simple check for this config, and submit a PR to at least call it out and probably abort early.

**Comment by ezyang** [comment]
Aha! The best fix is to manually specify an appropriate refspec when we fetch. Do you think you know how to construct that PR?

**Comment by amyreese** [comment]
I'll see what I can figure out tomorrow. I'll have to pay closer attention to what's happening with the git commands. 😅
