### ISSUE TITLE
ghstack said Fatal: unable to access 'https://github.com/pytorch/pytorch.git/'

### ISSUE THREAD

**Issue by XiaobingSuper** [ezyang/ghstack#15]
I want to use ghstack to pull a series of commits to PyTorch as the following step:

1. git clone https://github.com/pytorch/pytorch.git
2. prepare my commits
3. run ghstack

but I get the following error:
```
From https://github.com/pytorch/pytorch
   79d47c1..7e55494  master     -> origin/master
 + 272f3a2...b91ecc0 true_division -> origin/true_division  (forced update)
$ git merge-base origin/master HEAD
$ git rev-list --header ^79d47c1c5ff5306bdd275196b7171c04bebbdcca HEAD
$ git rev-list --header ^79d47c1c5ff5306bdd275196b7171c04bebbdcca^@ 79d47c1c5ff5306bdd275196b7171c04bebbdcca
$ git for-each-ref refs/remotes/origin/gh/xiaobingsuper --format=%(refname)
$ git rev-parse f7bc54125a83ac499570e7dcf7863b4ba613d544~^{tree}
$ git commit-tree 44e36f68d40a59b55c43ea9bba7048ca6749dd8e -p 79d47c1c5ff5306bdd275196b7171c04bebbdcca
$ git push origin b8904886ab258623abe263b9bd57c1168270e0c6:refs/heads/gh/xiaobingsuper/1/head 79d47c1c5ff5306bdd275196b7171c04bebbdcca:refs/heads/gh/xiaobingsuper/1/base
Username for 'https://github.com': xiaobingsuper
Password for 'https://xiaobingsuper@github.com': 
remote: Permission to pytorch/pytorch.git denied to XiaobingSuper.
fatal: unable to access 'https://github.com/pytorch/pytorch.git/': The requested URL returned error: 403
ERROR: Fatal exception
Traceback (most recent call last):
  File "/home/xiaobing/anaconda3/envs/pytorch-test/lib/python3.7/site-packages/ghstack/logging.py", line 108, in manager
    yield
  File "/home/xiaobing/anaconda3/envs/pytorch-test/lib/python3.7/site-packages/ghstack/__main__.py", line 113, in main
    github_url=conf.github_url,
  File "/home/xiaobing/anaconda3/envs/pytorch-test/lib/python3.7/site-packages/ghstack/submit.py", line 206, in main
    submitter.prepare_updates()
  File "/home/xiaobing/anaconda3/envs/pytorch-test/lib/python3.7/site-packages/ghstack/submit.py", line 896, in prepare_updates
    self.process_new_commit(s)
  File "/home/xiaobing/anaconda3/envs/pytorch-test/lib/python3.7/site-packages/ghstack/submit.py", line 584, in process_new_commit
    *new_branches,
  File "/home/xiaobing/anaconda3/envs/pytorch-test/lib/python3.7/site-packages/ghstack/shell.py", line 271, in git
    return self._maybe_rstrip(self.sh(*(("git",) + args), **kwargs))
  File "/home/xiaobing/anaconda3/envs/pytorch-test/lib/python3.7/site-packages/ghstack/shell.py", line 212, in sh
    .format(' '.join(args), returncode)
RuntimeError: git push origin b8904886ab258623abe263b9bd57c1168270e0c6:refs/heads/gh/xiaobingsuper/1/head 79d47c1c5ff5306bdd275196b7171c04bebbdcca:refs/heads/gh/xiaobingsuper/1/base failed with exit code 128
```
it seems that I need apply a permission of PyTorch repro, perhaps I miss something. Thanks!

**Comment by ezyang** [comment]
Yes, you need write permissions. I've sent you an invite.

**Comment by wizzniu** [comment]
@ezyang I also meet this problem. Could you send me an invite too? 
`$ ghstack
$ git push upstream fbd25ec64432bfb8651cc324f1e53e9080bb8a16:refs/heads/gh/wizzniu/1/base 9c0bfbff31bc66360f617d3d65399be3cb7550e7:refs/heads/gh/wizzniu/1/head
ERROR: Permission to pytorch/pytorch.git denied to wizzniu.
fatal: Could not read from remote repository.`

**Comment by ezyang** [comment]
Unfortunately to use ghstack you need write access to the repo, which for obvious reasons I am only giving to established contributors. What do you want to stack? Consider just opening a regular PR

**Comment by wizzniu** [comment]
@ezyang Thanks for your reply. I just wanna submit a series of PRs using ghstack. Otherwise, I have to open 2th PR until the first PR is merged.
