### ISSUE TITLE
Remove explicit references to 'master' in the codebase

### ISSUE THREAD

**Issue by ezyang** [ezyang/ghstack#35]

**Comment by samestep** [comment]
Working on this right now, since [GitHub now names the default branch `main` by default](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/). Example failure message when running `ghstack` in a new GitHub repo:
```
$ git remote get-url origin
$ git fetch origin
$ git merge-base origin/master HEAD
fatal: Not a valid object name origin/master
ERROR: Fatal exception
Traceback (most recent call last):
  File "/Users/sestep/github/ezyang/ghstack/ghstack/logging.py", line 108, in manager
    yield
  File "/Users/sestep/github/ezyang/ghstack/ghstack/__main__.py", line 115, in main
    remote_name=conf.remote_name,
  File "/Users/sestep/github/ezyang/ghstack/ghstack/submit.py", line 180, in main
    base = GitCommitHash(sh.git("merge-base", f"{remote_name}/{default_branch}", "HEAD"))
  File "/Users/sestep/github/ezyang/ghstack/ghstack/shell.py", line 272, in git
    return self._maybe_rstrip(self.sh(*(("git",) + args), **kwargs))
  File "/Users/sestep/github/ezyang/ghstack/ghstack/shell.py", line 213, in sh
    .format(' '.join(args), returncode)
RuntimeError: git merge-base origin/master HEAD failed with exit code 128
```
